<template>
  <svg viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg">
    <rect fill="none" height="256" width="256" />
    <circle
      cx="128"
      cy="128"
      fill="none"
      r="96"
      stroke="currentColor"
      stroke-linecap="round"
      stroke-linejoin="round"
      stroke-width="13"
    />
    <circle
      cx="128"
      cy="120"
      fill="none"
      r="40"
      stroke="currentColor"
      stroke-linecap="round"
      stroke-linejoin="round"
      stroke-width="13"
    />
    <path
      d="M63.8,199.4a72,72,0,0,1,128.4,0"
      fill="none"
      stroke="currentColor"
      stroke-linecap="round"
      stroke-linejoin="round"
      stroke-width="13"
    />
  </svg>
</template>
